---
title: "The States That Support Their Own"
subtitle: "Mini Project 2"
author: "Cai Ytsma, Juliane Bombosh, Sofia Salcedo"
date: "3/22/2018"
output: html_document
  code_folding: hide
---
##Goal
We are looking at the top 5 states for democratic and republican parties that had the highest number of donations by donors from the same state as the candidates they were donating to. 

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(ggplot2)
library(fiftystater)
```

```{r, label = "dataset import"}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, label = "state list"}
state_list <- c("AL", "AZ", "AR", "CA", "CO", "CT",
               "DE", "FL", "GA", "HI", "ID",
               "IL", "IN", "IA", "KS", "KY", "LA", "ME",
               "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE",
               "NV", "NH", "NJ", "NM", "NY", "NC", "ND",
               "OH", "OK", "OR", "PA", "RI", "SC", 
               "SD", "TN", "TX", "UT", "VT", "VA", "WA", 
               "WV", "WI", "WY")
```

```{r, label = "prepare datasets for merge"}
contribution_code <- contributions %>%
  select(cand_id, state) %>%
  group_by(state) %>%
  mutate(donor_state = state)

candidate_code <- candidates %>%
  mutate(party = cand_party_affiliation) %>%
  filter(party == "DEM" | party == "REP") %>%
  select(cand_id, party, cand_state)
```

```{r, label = "merge data and extract info"}
contributions_state <- contribution_code %>%
  left_join(candidate_code, by = "cand_id") %>%
  filter(donor_state == cand_state, cand_state %in% state_list) %>%
  select(-donor_state) %>%
  mutate(state.2 = cand_state) %>%
  group_by(party, state) %>%
  summarize(sum = n(), num_cand = n_distinct(cand_id)) %>%
  mutate(don_cand = round(sum / num_cand)) %>%
  select(-sum, -num_cand)
```

```{r, label = "prepare data for graphic"}
dem_map <- contributions_state %>%
  filter(party == "DEM") %>%
  select(-party)

rep_map <- contributions_state %>%
  filter(party == "REP") %>%
  select(-party)
```

```{r, label = "plot graphics"}
states <- map_data("state")
#make function that assigns color (red/blue) and alpha (don_cand) to each region (state)
ggplot(data = states) +
  geom_polygon(aes(x = long, y = lat, fill = region), color = "white") +
  coord_fixed(1.3) +
  guides(fill = FALSE) #remove legend
```

<<<<<<< HEAD
=======
>>>>>>> 74d8768889c2a5d9509df4174effa16ff47d8ae4

```{r, label = "Addin Functions"}
insertInAddin <- function() {
  rstudioapi::insertText(" %in% ")
}

wordcountaddin <- function(){
  wordcountaddin::text_stats("my_file.Rmd")}

```

```{r}
#this is a sample data. 
data("fifty_states") # this line is optional due to lazy data loading

crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)

# map_id creates the aesthetic mapping to the state name column in your data
p <- ggplot(crimes, aes(map_id = state)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = Assault), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())

p
# add border boxes to AK/HI
p + fifty_states_inset_boxes() 
```

```{r}
data("fifty_states") # the issue that needs to be addressed. REP has 49 data values and DEM has 48. Which is an issue if we use fiftystater. I do not think that the issue is that the state labels are different. Fiftystater has the name of the state lower case and we have the abbrieviation. SO we could... fix that with join but I don't think that will fix it. So we gotta fixure out why there is missing data through the filtering process or we gotta see if we can somehow override this so that it doesn't return the error "neg interger."kk ily J
Demoncracy1 <- data.frame(state = tolower(rownames(dem_map)), dem_map)

# map_id creates the aesthetic mapping to the state name column in your data
p <- ggplot(Demoncracy1, aes(map_id = state)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = don_cand), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())

p
# add border boxes to AK/HI
p + fifty_states_inset_boxes() 


```

=======
>>>>>>> 98e5865176d52f1c0f5f67f5113145b4040791a6
